[tool]
id = "com.thelightphone.tool_ci_fixture"
label = "Light Tool CI Fixture"
versionCode = 1001
versionName = "1.0.0"
permissions = ["android.permission.INTERNET"]
capabilities = []
# change if you run this on an LP3!
serverPackage = "com.lightos"
# serverPackage = "com.thelightphone.sdk.emulator"
